---
title: "08_amr_significance"
author: "Elisa Rubio"
date: "2022-09-12"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(cache=FALSE,
                      echo=TRUE, warning=FALSE, message=FALSE, results ='markup')
options(warn=-1)
```

```{r message=FALSE}
library(tidyverse)
library(kableExtra)
library(vegan)
library(ggpubr)
library(glue)
library(patchwork)
library(ggstatsplot)
library(broom)
```

#### Load data

```{r}
load("output/summarized_ariba.RDA")
load("output/rarefied_ariba.RDA")
load("output/ariba_dist.RDA")
metadata<-read_csv("data/Metadata/metadata.csv")
```

## Test each AMR gene separatedly for clinical variable (function)

### Dicotomic variable

```{r}
sig_AMR_clin_dic<-function(data, metadata, refdata, clin_var){

##transpose data
  ref_name<-pull(data, ref_name)
  data<-as_tibble(cbind(SampleID = names(data), t(data)))%>%slice(-1)%>%
    mutate_at(vars(-("SampleID")),as.numeric)
  colnames(data)<-c("SampleID", ref_name)

##merge data with metadata and reference data    
  data_all<-data%>%
    pivot_longer(-SampleID, names_to = "ref_name", values_to = "value")%>%
    inner_join(., metadata, by="SampleID")%>%
    inner_join(., refdata, by="ref_name")
  
  sig_amr<-data_all%>%
    nest(data=-ref_name)%>%
    mutate(test=map(.x=data, ~wilcox.test(value~!!ensym(clin_var), data=.x)%>%tidy))%>%
    unnest(test)%>%
    mutate(p.adjust=p.adjust(p.value, method = "BH"))%>%
    filter(p.adjust<0.05)%>%
    select(ref_name, p.adjust)
  
  data_all<-data_all%>%
  inner_join(sig_amr, by="ref_name")
  
  sig_amr<-sig_amr%>%
    inner_join(refdata, by="ref_name")
  
  res<-list(data_all, sig_amr)
  names(res)<-c("data_plot", "sig_amr")
  return(res)
  }
```

### Factor (>2 levels)

```{r}
sig_AMR_clin_factor<-function(data, metadata, refdata, clin_var){

##transpose data
  ref_name<-pull(data, 1)
  data<-as_tibble(cbind(SampleID = names(data), t(data)))%>%slice(-1)%>%
    mutate_at(vars(-("SampleID")),as.numeric)
  colnames(data)<-c("SampleID", ref_name)

##merge data with metadata and reference data    
  data_all<-data%>%
    pivot_longer(-SampleID, names_to = "ref_name", values_to = "value")%>%
    inner_join(., metadata, by="SampleID")%>%
    inner_join(., refdata, by="ref_name")
  
  sig_amr<-data_all%>%
    nest(data=-ref_name)%>%
    mutate(test=map(.x=data, ~kruskal.test(value~!!ensym(clin_var), data=.x)%>%tidy))%>%
    unnest(test)%>%
    mutate(p.adjust=p.adjust(p.value, method = "BH"))%>%
    filter(p.adjust<0.05)%>%
    select(ref_name, p.adjust)
  
  data_all<-data_all%>%
  inner_join(sig_amr, by="ref_name")
  
  sig_amr<-sig_amr%>%
    inner_join(refdata, by="ref_name")
  
  res<-list(data_all, sig_amr)
  names(res)<-c("data_plot", "sig_amr")
  return(res)
  }
```

## Microbiome cluster

```{r}
amr_sig_cluster<-sig_AMR_clin_dic(ariba_rpkm, filter(metadata, !is.na(Cluster)), refname_all_ariba, Cluster)
amr_sig_cluster$sig_amr %>% kable(caption="**Significant AMR genes, microbiome cluster (Ariba RPKM**")%>%kable_paper("striped")%>%scroll_box(width = "100%", height = "500px")
```


```{r, out.width="100%"}
amr_sig_cluster$data_plot%>%
  ggplot(aes(x=Cluster, y=value, color=Cluster)) +
  geom_boxplot(outlier.shape = NA, show.legend = FALSE)+
  geom_jitter(position = position_jitterdodge(dodge.width = 0.8,
                                              jitter.width = 0.5))+
  
  ##scale_y_log10() +
  facet_wrap(~`ARO Term`, scales = "free_y")+
  # scale_color_manual(NULL,
  #                    breaks = c(F, T),
  #                    values = c("gray", "dodgerblue"),
  #                    labels = c("Healthy", "SRN")) +
  # scale_fill_manual(NULL,
  #                    breaks = c(F, T),
  #                    values = c("gray", "dodgerblue"),
  #                    labels = c("Healthy", "SRN")) +
  labs(x= "RPKM values", y=NULL) +
  theme_bw()+
  theme(axis.text.x = element_text(angle=45, hjust = 1))

```


## Riskgroup2

```{r}
amr_sig_riskgroup<-sig_AMR_clin_factor(ariba_rpkm, metadata, refname_all_ariba, RiskGroup2)
amr_sig_riskgroup$sig_amr %>% kable(caption="**Significant AMR genes, riskgroup2 (Ariba RPKM**")%>%kable_paper("striped")%>%scroll_box(width = "100%", height = "500px")
```

```{r, out.width="100%"}
amr_sig_riskgroup$data_plot%>%
  ggplot(aes(x=RiskGroup2, y=value, color=RiskGroup2)) +
  geom_boxplot(outlier.shape = NA, show.legend = FALSE)+
  geom_jitter(position = position_jitterdodge(dodge.width = 0.8,
                                              jitter.width = 0.5))+
  
  ##scale_y_log10() +
  facet_wrap(~`ARO Term`, scales = "free_y")+
  # scale_color_manual(NULL,
  #                    breaks = c(F, T),
  #                    values = c("gray", "dodgerblue"),
  #                    labels = c("Healthy", "SRN")) +
  # scale_fill_manual(NULL,
  #                    breaks = c(F, T),
  #                    values = c("gray", "dodgerblue"),
  #                    labels = c("Healthy", "SRN")) +
  labs(x= "RPKM values", y=NULL) +
  theme_bw()+
  theme(axis.text.x = element_text(angle=45, hjust = 1))
```

