---
title: "corplot"
author: "Elisa Rubio"
date: "2022-03-02"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(cache=FALSE,
                      echo=TRUE, warning=FALSE, message=FALSE, eval=FALSE, results ='markup')
options(warn=-1)
```

```{r message=FALSE}
library(tidyverse)
library(kableExtra)
library(corrplot)
library(Hmisc)
```

```{r}
load("output/summarized_data.RDA")
ref_name<-pull(ariba_rpkm, ref_name); ariba_rpkm<-select(ariba_rpkm, -ref_name); rownames(ariba_rpkm)<-ref_name
```

```{r}
res2 <- rcorr(as.matrix(t(ariba_rpkm)))

```

```{r}
flattenCorrMatrix <- function(cormat, pmat) {
  ut <- upper.tri(cormat)
  data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
    )
}

x<-flattenCorrMatrix(res2$r, res2$P)%>%mutate(padj=p.adjust(p, method = "BH"))%>%filter(padj<0.01 & abs(cor)> 0.5)
x<-x%>%select(-p, -padj)%>%pivot_wider(names_from = column, values_from = cor)%>%as.matrix()
class(x)

mtx_corr <- reshape2::acast(x, row~column, value.var="cor")

corrplot(mtx_corr, is.corr=FALSE, tl.col="black", na.label=" ")
```


```{r}
corr = cor(t(ariba_rpkm))
corr[lower.tri(corr,diag=TRUE)] <- NA 
corr[corr == 1] <- NA 
corr <- as.data.frame(as.table(corr))
corr <- na.omit(corr) 
corr <- subset(corr, abs(Freq) > 0.5) 

```


```{r}
corr_simple <- function(data=df,sig=0.5){
  #convert data to numeric in order to run correlations
  #convert to factor first to keep the integrity of the data - each value will become a number rather than turn into NA
  df_cor <- data %>% mutate_if(is.character, as.factor)
  df_cor <- df_cor %>% mutate_if(is.factor, as.numeric)
  #run a correlation and drop the insignificant ones
  corr <- cor(df_cor)
  #prepare to drop duplicates and correlations of 1     
  corr[lower.tri(corr,diag=TRUE)] <- NA 
  #drop perfect correlations
  corr[corr == 1] <- NA 
  #turn into a 3-column table
  corr <- as.data.frame(as.table(corr))
  #remove the NA values from above 
  corr <- na.omit(corr) 
  #select significant values  
  corr <- subset(corr, abs(Freq) > sig) 
  #sort by highest correlation
  corr <- corr[order(-abs(corr$Freq)),] 
  #print table
  print(corr)
  #turn corr back into matrix in order to plot with corrplot
  mtx_corr <- reshape2::acast(corr, Var1~Var2, value.var="Freq")
  
  #plot correlations visually
  corrplot(mtx_corr, is.corr=FALSE, tl.col="black", na.label=" ")
}
corr_simple()
```


https://towardsdatascience.com/how-to-create-a-correlation-matrix-with-too-many-variables-309cc0c0a57
