---
title: "Riskgroup2_grouped"
author: "Elisa Rubio"
date: "2022-11-13"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(cache=FALSE,
                      echo=TRUE, warning=FALSE, message=FALSE, results ='markup')
options(warn=-1)
```

```{r message=FALSE}
library(tidyverse)
library(kableExtra)
library(vegan)
library(ggpubr)
library(glue)
library(patchwork)
library(ggstatsplot)
library(broom)
```

#### Load data and functions

```{r}
load("output/summarized_ariba.RDA")
load("output/rarefied_ariba.RDA")
load("output/ariba_dist.RDA")
load("output/grouped_rpkm_ariba.RDA")
metadata<-read_csv("data/Metadata/metadata.csv")
source("code/functions.R")
```

## Join HTS with PWID

```{r}
metadata<-metadata%>%
  mutate(MSM_dic=ifelse(RiskGroup2=="msm", "MSM", "no MSM"))
```

### Alpha diversity analysis

```{r}
ariba_alpha_rpkm<-alpha_div(ariba_rpkm, ariba_counts, metadata)
alpha_div_plot_all(ariba_alpha_rpkm, MSM_dic)
```

Diversity is higher in MSM group

```{r eval=FALSE, include=FALSE}
## ECCMID figure:
  ariba_alpha_rpkm%>%
    filter(!is.na(MSM_dic))%>%
    ggplot(aes(x=MSM_dic, y=InvSimpson))+
    geom_boxplot(aes(colour=MSM_dic, fill=MSM_dic, alpha=0.2), outlier.shape = NA)+
    geom_jitter(width = 0.2, aes(colour=MSM_dic))+
    scale_color_manual(values = c("red", "gray48"))+
    scale_fill_manual(values = c("pink", "gray80"))+
    stat_compare_means(label="p.format", label.x.npc =  'center', label.y.npc = 0.9, size=5)+
    theme_bw()+
    theme(legend.position = "none", text = element_text(size = 15))+
    labs(y="Inverse Simpson", x=element_blank())

ggsave("ECCMID_figures/alpha_div.tiff", height = 5.5, width = 4)
```


### Beta diversity analysis

```{r}
ariba_dist_rpkm<-ariba_dist$dist_rpkm
beta_nmds(ariba_dist_rpkm, metadata, MSM_dic)
```

Resistome composition is different according to MSM

```{r}
##ECCMID figure
  dist_df<-as.data.frame(as.matrix(ariba_dist_rpkm)); dist_df$SampleID<-rownames(dist_df)
  meta_dist<-inner_join(metadata, dist_df, by="SampleID")%>%
    filter(!is.na(MSM_dic))

  dist<-meta_dist%>%
    select(all_of(.[["SampleID"]]))%>%
    as.dist()

  clin_var2<-meta_dist%>%pull(MSM_dic) ##clin_var vector for adonis test

  test<-adonis(dist~clin_var2, permutations = 999)
  ptest<-test$aov.tab$`Pr(>F)`[1]
  r2test<-round(test$aov.tab$R2[1],2)

  set.seed(200889)
  nmds <- metaMDS(dist, trace = 0)

  ##scores(nmds) %>%
  nmds$points %>%
    as_tibble(rownames = "SampleID") %>%
    rename(NMDS1=MDS1, NMDS2=MDS2) %>%
    inner_join(., metadata, by="SampleID") %>%
    filter(!is.na(MSM_dic))%>%
    ggplot(aes(x=NMDS1, y=NMDS2, color=MSM_dic, fill=MSM_dic)) +
    stat_ellipse(geom="polygon", show.legend = FALSE, alpha=0.2)+
    geom_point()+
    coord_fixed(ratio = 0.8)+
    annotate("text", x = -0.35, y = 0.4, label = glue("ADONIS p={ptest} \n r2={r2test}"), size=4, hjust=0)+
    scale_color_manual(name="Sexual \nPractice",
                      values = c("red", "gray48"))+
    scale_fill_manual(name="Sexual \nPractice", 
                      values = c("pink", "gray80"))+
    theme_bw()+
    theme(text = element_text(size=15))
  
ggsave("ECCMID_figures/beta_div.tiff", height = 5.5, width = 6)
```


## Check differentially abundance AMR

```{r}
amr_sig_rpkm_MSM_dic<-sig_AMR_clin_dic(ariba_rpkm, metadata, refname_all_ariba, MSM_dic)
amr_sig_rpkm_MSM_dic$sig_amr%>% kable(caption="**Significant AMR accordig to Gene Richness (Ariba RPKM**")%>%kable_paper("striped")%>%scroll_box(width = "100%", height = "500px")
```


## Check differentially abundance (grouped by Drug Class)

```{r}
drugclass_sig_rpkm_MSM_dic<-sig_group_clin_dic(ariba_rpkm_drugclass, metadata, MSM_dic)
drugclass_sig_rpkm_MSM_dic$sig_data%>% kable(caption="**Significant Drug Classes, MSM (Ariba RPKM)**")%>%kable_paper("striped")%>%scroll_box(width = "100%", height = "500px")


drugclass<-drugclass_sig_rpkm_MSM_dic$sig_data
write_excel_csv(drugclass, "output/ECCMID_data/drugclass.xlsx")
```

```{r}
drugclass_sig_rpkm_MSM_dic$data_plot%>%
  ggplot(aes(x=MSM_dic, y=value, color=MSM_dic)) +
  geom_boxplot(outlier.shape = NA, show.legend = FALSE)+
  geom_jitter(position = position_jitterdodge(dodge.width = 0.8,
                                              jitter.width = 0.5))+
  stat_compare_means(label.y.npc = 0.7, label = "p.signif")+
  facet_wrap(~group_name, scales = "free_y")+
  labs(x= "RPKM values", y=NULL, title="ARIBA RPKM") +
  theme_bw()+
  theme(axis.text.x = element_text(angle=45, hjust = 1))
```


## Check differentially abundance (grouped by Gene Family)

```{r}
##Unify the two gene families with mutations at 23S
rRNA23S<-ariba_rpkm_genefamily%>%
  filter(`AMR Gene Family` ==  
"23S rRNA with mutation conferring resistance to macrolide antibiotics" | `AMR Gene Family`== "23S rRNA with mutation conferring resistance to pleuromutilin antibiotics") %>% 
  summarise(across(where(is.numeric), sum))%>% 
  mutate(`AMR Gene Family`= "23S rRNA mutation")%>%select(`AMR Gene Family`, everything())

ariba_rpkm_genefamily<-rbind(ariba_rpkm_genefamily, rRNA23S)


genefamily_sig_rpkm_MSM_dic<-sig_group_clin_dic(ariba_rpkm_genefamily, metadata, MSM_dic)

##Add Drug Class to gene family diff table:
##Create database (refname) grouped by gene family 
refname<-refname_all_ariba%>%
  select(group_name=`AMR Gene Family`, `Drug Class`, `ARO Term`)%>%
  unique()%>%
  as_tibble()%>%
  group_by(group_name)%>%
  mutate(`Drug Class`=paste0(`Drug Class`, collapse = ","),
         `ARO Term`= paste0(`ARO Term`, collapse = ","))%>%
  unique()

genefamily_sig_rpkm_MSM_dic$sig_data%>%left_join(refname, by = "group_name")%>%rename(Gene_Family=group_name)%>% kable(caption="**Significant Gene Families, MSM (Ariba RPKM**")%>%kable_paper("striped")%>%scroll_box(width = "100%", height = "500px")

# genefamily<-genefamily_sig_rpkm_MSM_dic$sig_data%>%left_join(refname, by = "group_name")%>%rename(Gene_Family=group_name)
# write_excel_csv(genefamily, "output/ECCMID_data/genefamily.xlsx")
```

```{r}
genefamily_sig_rpkm_MSM_dic$data_plot%>%
  ggplot(aes(x=MSM_dic, y=value, color=MSM_dic)) +
  geom_boxplot(outlier.shape = NA, show.legend = FALSE)+
  geom_jitter(position = position_jitterdodge(dodge.width = 0.8,
                                              jitter.width = 0.5))+
  stat_compare_means(label.y.npc = 0.7, label = "p.signif")+
  facet_wrap(~group_name, scales = "free_y")+
  labs(x= "RPKM values", y=NULL, title="ARIBA RPKM") +
  theme_bw()+
  theme(axis.text.x = element_text(angle=45, hjust = 1))
```

## ECCMID figure

```{r}
atbs<-c("cephalosporin", "cephamycin", "penam", "glycopeptide antibiotic", "mupirocin", "sulfonamide antibiotic", "aminoglycoside antibiotic")



table<-drugclass_sig_rpkm_MSM_dic$sig_data%>%
  filter(group_name %in% atbs)%>%
  mutate(group_name2=case_when(
  group_name == "cephalosporin"~ "Cephalosporin",
  group_name == "cephamycin"~ "Cephamycin",
  group_name == "penam"~ "Penam",
  group_name == "glycopeptide antibiotic"~ "Glycopeptide",
  group_name == "mupirocin"~ "Mupirocin",
  group_name == "sulfonamide antibiotic"~ "Sulfonamide",
  group_name == "aminoglycoside antibiotic"~ "Aminoglycoside",
  ))%>%
  mutate(p_adjust=round(p.adjust, 2), 
         p_adjust=as.character(p_adjust),
    p_adjust2=ifelse(p_adjust=="0", "<0.005", glue("={p_adjust}")),
 label=glue("p{p_adjust2}\nlog2FC={round(log2f,2)}"))
  

drugclass_sig_rpkm_MSM_dic$data_plot%>%
  filter(group_name %in% atbs)%>%
mutate(group_name2=case_when(
  group_name == "cephalosporin"~ "Cephalosporin",
  group_name == "cephamycin"~ "Cephamycin",
  group_name == "penam"~ "Penam",
  group_name == "glycopeptide antibiotic"~ "Glycopeptide",
  group_name == "mupirocin"~ "Mupirocin",
  group_name == "sulfonamide antibiotic"~ "Sulfonamide",
  group_name == "aminoglycoside antibiotic"~ "Aminoglycoside",
  ))%>%
  ggplot(aes(x=MSM_dic, y=value, color=MSM_dic)) +
  geom_boxplot(outlier.shape = NA, show.legend = FALSE)+
  geom_jitter(position = position_jitterdodge(dodge.width = 0.8,
                                              jitter.width = 0.5))+
   scale_color_manual(name="Sexual \nPractice",
                      values = c("red", "gray48"))+
    scale_fill_manual(name="Sexual \nPractice", 
                      values = c("pink", "gray80"))+
  facet_wrap(~group_name2, scales = "free_y")+
    geom_text(data= table,
    mapping = aes(x = Inf, y = Inf, label = label),
    hjust   = 1.1,
    vjust   = 1.1, inherit.aes = FALSE)+
  labs(y= "RPKM values", x=NULL) +
  theme_bw()+
  theme(axis.text.x = element_text(angle=45, hjust = 1), legend.position = "none", text = element_text(size=15))

ggsave("ECCMID_figures/drugclass_diff.tiff", height = 10, width = 10)
```





